#!/bin/bash
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root. Use sudo:"
    echo -e "run:\nsudo $0 $@"
    exit 1
fi

DEVICE="/dev/input/event2"  # replace with your keyboard device

sudo evtest "$DEVICE" | while read -r line; do
  if echo "$line" | grep -q "KEY_PROG2.*value 1"; then
    echo "TurboKey pressed!"
    if [[ $(cat /sys/class/hwmon/hwmon3/fan1_input) -lt 2500 ]]; then
	   fan -s 100
    else
	   fan -s 15
    fi
  fi
done
